export const GAME_STATE = {
  MAIN_MENU: 'MAIN_MENU',
  README: 'README',
  SCOREBOARD: 'SCOREBOARD',
  STORY: 'STORY',
  READY: 'READY',
  PLAYING: 'PLAYING',
  GAME_OVER: 'GAME_OVER',
  STAGE_CLEAR: 'STAGE_CLEAR',
  STAGE_FAILED: 'STAGE_FAILED',
  ENDING: 'ENDING',
  PAUSED: 'PAUSED',
}

export const GAME_MODE = {
  STORY: 'STORY',
  EXTRA_STORY: 'EXTRA_STORY',
  CHALLENGE_DADA: 'CHALLENGE_DADA',
  CHALLENGE_YODA: 'CHALLENGE_YODA',
  CHALLENGE_REAL: 'CHALLENGE_REAL',
}

export const LOCAL_STORAGE_KEY = {
  UNLOCK_REAL_CHALLENGE: 'UNLOCK_REAL_CHALLENGE',
  UNLOCK_EXTRA_STORY: 'UNLOCK_EXTRA_STORY',
}

export const DEFAULT_LIVES = 3
export const MAX_LIVES = 9
export const TOP_BORDER_HEIGHT = 0
export const SCREEN_WIDTH = 1280
export const SCREEN_HEIGHT = 960 - TOP_BORDER_HEIGHT
export const BLOCK_WIDTH = 64
export const BLOCK_HEIGHT = 32
export const ITEM_WIDTH = 48
export const ITEM_HEIGHT = 48
export const PADDLE_DEFAULT_X = 600
export const PADDLE_DEFAULT_Y = 900
export const PADDLE_DEFAULT_WIDTH = 192 // 64 + 64 + 64
export const PADDLE_UNIT_WIDTH = 64
export const PADDLE_MIN_WIDTH = 64
export const PADDLE_MAX_WIDTH = 384
export const PADDLE_YODA_DEFAULT_WIDTH = 128
export const PADDLE_YODA_MIN_WIDTH = 64
export const PADDLE_YODA_MAX_WIDTH = 128
export const PADDLE_HEIGHT = 32
export const PADDLE_IMG_WIDTH = 256
export const PADDLE_IMG_HEIGHT = 73
export const BALL_IMAGE_RADIUS = 32
export const BALL_DEFAULT_RADIUS = 24
export const BALL_MIN_RADIUS = 8
export const BALL_MAX_RADIUS = 56
export const BALL_UNIT_RADIUS = 16
export const ACCELERATION = 1.01
export const DEFAULT_SPEED = 5
export const REAL_DEFAULT_SPEED = 7.5
export const SPEED_MULTIPLIER = 1.5
export const MIN_SPEED = 3
export const MAX_SPEED = 20
export const ITEM_DROP_SPEED_FROM = 2
export const ITEM_DROP_SPEED_TO = 4
export const BULLET_ATK = 2
export const BULLET_SPEED = 5
export const BULLET_WIDTH = 30
export const BULLET_HEIGHT = 40
export const BULLET_OFFSET = 32
export const BULLET_IMG_WIDTH = 48
export const BULLET_IMG_HEIGHT = 64
export const BULLET_DEFAULT_COUNT = 5
export const BULLET_MAX_COUNT = 99
export const BULLET_RELOAD_COUNT = 10
export const DELTA_UNIT = 0.42

export const DROP_RATIO_BUFF = 0.1
export const DROP_RATIO_DEBUFF = 0.1
export const DROP_RATIO_MONEY_XS = 0.3
export const DROP_RATIO_MONEY_SM = 0.2
export const DROP_RATIO_MONEY_MD = 0.15
export const DROP_RATIO_MONEY_LG = 0.1
export const DROP_RATIO_MONEY_XL = 0.05

export const BLOCK = {
  NORMAL_1: 'NORMAL_1',
  NORMAL_2: 'NORMAL_2',
  NORMAL_2_1: 'NORMAL_2_1',
  NORMAL_3: 'NORMAL_3',
  NORMAL_3_1: 'NORMAL_3_1',
  NORMAL_3_2: 'NORMAL_3_2',
  STONE: 'STONE',
}

export const BLOCK_HP = {
  [BLOCK.NORMAL_1]: 2,
  [BLOCK.NORMAL_2]: 4,
  [BLOCK.NORMAL_3]: 6,
  [BLOCK.STONE]: Infinity,
}

export const BALL_COLOR = {
  BLUE: 'BALL_COLOR_BLUE',
  RED: 'BALL_COLOR_RED',
  BLACK: 'BALL_COLOR_BLACK',
}

export const BALL_ATK = {
  [BALL_COLOR.BLUE]: 2,
  [BALL_COLOR.RED]: 6,
  [BALL_COLOR.BLACK]: 1,
}

export const ITEM = {
  BULLET_PACK: 'ITEM_BULLET_PACK',
  PADDLE_PLUS: 'ITEM_PADDLE_PLUS',
  PADDLE_MINUS: 'ITEM_PADDLE_MINUS',
  BALL_DOUBLE: 'ITEM_BALL_DOUBLE',
  BALL_RED: 'ITEM_BALL_RED',
  BALL_BLUE: 'ITEM_BALL_BLUE',
  BALL_BLACK: 'ITEM_BALL_BLACK',
  BALL_LARGE: 'ITEM_BALL_LARGE',
  BALL_SMALL: 'ITEM_BALL_SMALL',
  SPEED_PLUS: 'ITEM_SPEED_PLUS',
  SPEED_MINUS: 'ITEM_SPEED_MINUS',
  UNKNOWN: 'ITEM_UNKNOWN',
  MONEY_XS: 'ITEM_MONEY_XS',
  MONEY_SM: 'ITEM_MONEY_SM',
  MONEY_MD: 'ITEM_MONEY_MD',
  MONEY_LG: 'ITEM_MONEY_LG',
  MONEY_XL: 'ITEM_MONEY_XL',
}

export const BUFF_ITEMS = [
  ITEM.BULLET_PACK,
  ITEM.BALL_RED,
  ITEM.BALL_LARGE,
  ITEM.SPEED_MINUS,
  ITEM.PADDLE_PLUS,
  ITEM.BALL_DOUBLE,
]

export const DEBUFF_ITEMS = [
  ITEM.BALL_BLUE,
  ITEM.BALL_BLACK,
  ITEM.BALL_SMALL,
  ITEM.SPEED_PLUS,
  ITEM.PADDLE_MINUS,
]

export const REAL_BUFF_ITEMS = BUFF_ITEMS.filter(item => ![ITEM.BULLET_PACK, ITEM.PADDLE_PLUS].includes(item))

export const REAL_DEBUFF_ITEMS = DEBUFF_ITEMS.filter(item => item !== ITEM.PADDLE_MINUS)

export const MONEY_VALUES = {
  [ITEM.MONEY_XS]: 1000,
  [ITEM.MONEY_SM]: 4000,
  [ITEM.MONEY_MD]: 10000,
  [ITEM.MONEY_LG]: 40000,
  [ITEM.MONEY_XL]: 200000,
}
